CREATE TABLE "ACCOUNTS"
  (
    "ID"          NUMBER(*,0) NOT NULL ENABLE,
    "M_ID"        NUMBER(*,0) NOT NULL ENABLE,
    "ACCOUNT"     VARCHAR2(255 BYTE) NOT NULL ENABLE,
    "PASSWORD"    VARCHAR2(255 BYTE) NOT NULL ENABLE,
    "STATUS"      NUMBER(*,0) NOT NULL ENABLE,
    "ERROR_TIMES" NUMBER(*,0) NOT NULL ENABLE,
    "TIME_LAST"   TIMESTAMP (6) NOT NULL ENABLE,
    "TIME_BUILD"  TIMESTAMP (6) NOT NULL ENABLE,
    "TIME_MODIFY" TIMESTAMP (6) NOT NULL ENABLE,
    CONSTRAINT "ACCOUNTS_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 TABLESPACE "USERS" ENABLE,
    CONSTRAINT "ACCOUNTS_FK1" FOREIGN KEY ("M_ID") REFERENCES "MEMBERS" ("ID") ENABLE
  )
  SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS" ;

CREATE SEQUENCE accounts_id_seq;
