CREATE TABLE "ACC_JOURNALS"
  (
    "ID"          NUMBER(*,0) NOT NULL ENABLE,
    "TIME_DATE"   TIMESTAMP (6) NOT NULL ENABLE,
    "DEBIT"       NUMBER(*,0) NOT NULL ENABLE,
    "CREDIT"      NUMBER(*,0) NOT NULL ENABLE,
    "AMOUNT"      NUMBER(*,0) NOT NULL ENABLE,
    "ITEM"        VARCHAR2(1023 BYTE) NOT NULL ENABLE,
    "PLACE"       VARCHAR2(255 BYTE),
    "WHO"         VARCHAR2(255 BYTE),
    "A_ID"        NUMBER(*,0) NOT NULL ENABLE,
    "TIME_BUILD"  TIMESTAMP (6) NOT NULL ENABLE,
    "TIME_MODIFY" TIMESTAMP (6) NOT NULL ENABLE,
    CONSTRAINT "ACC_JOURNALS_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 TABLESPACE "USERS" ENABLE,
    CONSTRAINT "ACC_JOURNALS_FK1" FOREIGN KEY ("DEBIT") REFERENCES "ACC_SUBJECTS" ("ID") ENABLE,
    CONSTRAINT "ACC_JOURNALS_FK2" FOREIGN KEY ("CREDIT") REFERENCES "ACC_SUBJECTS" ("ID") ENABLE,
    CONSTRAINT "ACC_JOURNALS_FK3" FOREIGN KEY ("A_ID") REFERENCES "ACCOUNTS" ("ID") ENABLE
  )
  SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS" ;

CREATE SEQUENCE acc_journals_id_seq;
