CREATE TABLE "MEMBERS"
  (
    "ID"          NUMBER(*,0) NOT NULL ENABLE,
    "NAME"        VARCHAR2(255 BYTE) NOT NULL ENABLE,
    "EMAIL"       VARCHAR2(255 BYTE) NOT NULL ENABLE,
    "PHONE"       VARCHAR2(255 BYTE) NOT NULL ENABLE,
    "TIME_MODIFY" TIMESTAMP (6) NOT NULL ENABLE,
    "TIME_BUILD"  TIMESTAMP (6) NOT NULL ENABLE,
    CONSTRAINT "MEMBERS_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 TABLESPACE "USERS" ENABLE
  )
  SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS" ;

CREATE SEQUENCE members_id_seq;
