COMMENT ON TABLE "ACC_SUBJECTS" IS '會計科目';

COMMENT ON COLUMN "ACC_SUBJECTS"."ID" IS '序號';
COMMENT ON COLUMN "ACC_SUBJECTS"."CODE" IS '科目代號';
COMMENT ON COLUMN "ACC_SUBJECTS"."NAME" IS '科目名稱';
COMMENT ON COLUMN "ACC_SUBJECTS"."TIME_BUILD" IS '建立日期';
COMMENT ON COLUMN "ACC_SUBJECTS"."TIME_MODIFY" IS '修改日期';

--data
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2','收支',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-1','收入',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-1-1','薪資收入',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-1-1-1','薩莉亞薪資',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-1-1-2','替代役薪資',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-1-1-3','教育部薪資',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-1-1-4','中華電信薪資',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-1-2','其他收入',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-1-2-1','利息收入',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-1-2-2','贊助收入',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-1-2-3','保險獲賠收入',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2','支出',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-1','伙食費',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-1-1','早餐',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-1-2','中餐',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-1-3','晚餐',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-1-4','飲品',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-1-5','點心',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-1-6','宵夜',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-2','交通費',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-2-1','悠遊卡',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-2-2','機車汽油',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-2-3','其他交通費',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-3','電話費',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-3-1','遠傳電信',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-4','社交費',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-4-1','聚餐',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-4-2','伴手禮',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-5','保險費',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-5-1','健康保險',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-5-2','機車強制險',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-5-3','壽險',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-5-4','失能險(殘廢扶助險)',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-5-5','醫療傷害險',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-6','投資費',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-6-1','基金',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-7','其他費用',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-7-1','家庭支用',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-7-2','特殊支用',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-7-3','設備費',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-7-4','學費',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-7-5','遊樂費',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-7-6','書籍費',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-7-7','治裝費',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-7-8','機車保養',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-7-9','R'||'&'||'D',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-8','呆帳',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'2-2-8-1','呆帳',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1','資產負債',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1-1','資產',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1-1-1','現金',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1-1-1-1','現金',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1-1-2','銀行存款',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1-1-2-1','郵局',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1-1-2-2','富邦銀行',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1-1-2-3','合作金庫',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1-1-2-4','上海商業銀行',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1-1-2-5','凱基銀行',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1-1-3','借出款項',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1-1-3-1','借出款項',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1-2','負債',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1-2-1','應付款項',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1-2-1-1','凱基銀行副卡',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1-2-1-2','凱基銀行卡',current_timestamp,current_timestamp);
INSERT INTO acc_subjects(id, code, name, time_build, time_modify) VALUES (acc_subjects_id_seq.nextval,'1-2-1-3','玉山銀行 Pi 卡',current_timestamp,current_timestamp);
